#!/usr/bin/env python
"""
Generated by 'esmerald createproject' using Esmerald 1.2.5.
"""
import os
import sys

from esmerald import Esmerald, Include


def build_path():
    """
    Builds the path of the project and project root.
    """
    SITE_ROOT = os.path.dirname(os.path.realpath(__file__))

    if SITE_ROOT not in sys.path:
        sys.path.append(SITE_ROOT)
        sys.path.append(os.path.join(SITE_ROOT, "apps"))


def get_application():
    """
    This is optional. The function is only used for organisation purposes.
    """
    build_path()

    app = Esmerald(
        routes=[Include(namespace="myproject.urls")],
    )
    return app


app = get_application()
