#!/bin/sh -e

if [ "$VIRTUAL_ENV" != '' ]; then
    export PREFIX="$VIRTUAL_ENV/bin/"
elif [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
else
    PREFIX=""
fi

set -x

${PREFIX}python -m build
${PREFIX}twine check dist/*
