#!/bin/sh -e

# Use the Python executable provided from the `-p` option, or a default.
[ "$1" = "-p" ] && PYTHON=$2 || PYTHON="python3"

VENV="venv"

set -x

if [ "$VIRTUAL_ENV" != '' ]; then
    PIP="$VIRTUAL_ENV/bin/pip"
elif [ -z "$GITHUB_ACTIONS" ]; then
    "$PYTHON" -m venv "$VENV"
    PIP="$VENV/bin/pip"
else
    PIP="pip"
fi

"$PIP" install -U pip
"$PIP" install -e .[all,dev,doc,test]
