#!/bin/sh

export PREFIX=""
if [ "$VIRTUAL_ENV" != '' ]; then
    export PREFIX="$VIRTUAL_ENV/bin/"
elif [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -ex

if [ -z $GITHUB_ACTIONS ]; then
    scripts/lint
fi

export ESMERALD_SETTINGS_MODULE='tests.settings.TestSettings'

${PREFIX}pytest $@

unset ESMERALD_SETTINGS_MODULE
