"""
Esmerald settings for myproject project.

Generated by 'esmerald createproject' using Esmerald 1.2.5.
"""

from typing import Optional

from esmerald.conf.enums import EnvironmentType
from esmerald.conf.global_settings import EsmeraldAPISettings


class AppSettings(EsmeraldAPISettings):
    app_name: str = "My application in production mode."
    title: str = "My myproject"
    environment: Optional[str] = EnvironmentType.PRODUCTION
    secret_key: str = "esmerald-insecure-2hd3=de5%v7h)64sem6te8hgk($)#)t$"
